version: '3.7'

services:
  app:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-converter-xml2json
    depends_on: [db]
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    networks:
      public:
    configs:
      - source: smart-village-app-converter-tmb-database-yml
        target: /app/config/database.yml
      - source: unicorn-5-worker
        target: /app/config/unicorn.rb
      - source: bad-belzig-tmb-importer-master-key
        target: /app/config/master.key
      - source: bad-belzig-tmb-importer-production-key
        target: /app/config/credentials/production.key
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - unicorn:/unicorn
      - assets:/assets
      - settings:/app/config/settings
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: 'postgres:10.3-alpine'
    environment:
      POSTGRES_USER: smart
      POSTGRES_PASSWORT: smart
      POSTGRES_DB: smart
    networks:
      public:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - db:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure

  cron:
    image: registry.gitlab.tpwd.de/ikusei/smart-village-app-converter-xml2json
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    entrypoint: sh
    command: bin/start-cron.sh
    depends_on: [db]
    configs:
      - source: smart-village-app-converter-tmb-database-yml
        target: /app/config/database.yml
      - source: unicorn-5-worker
        target: /app/config/unicorn.rb
      - source: bad-belzig-tmb-importer-master-key
        target: /app/config/master.key
      - source: bad-belzig-tmb-importer-production-key
        target: /app/config/credentials/production.key
    volumes:
      - settings:/app/config/settings

volumes:
  db:
  unicorn:
  assets:
  settings:

configs:
  smart-village-app-converter-xml2json-nginx-conf:
    external: true
  smart-village-app-converter-tmb-database-yml:
    external: true
  unicorn-5-worker:
    external: true
  bad-belzig-tmb-importer-master-key:
    external: true
  bad-belzig-tmb-importer-production-key:
    external: true

networks:
  public:
    external: true
