version: '3.7'

services:
  app:
    build:
      context: .
    environment:
      RAILS_ENV: development
    volumes:
      - ./docker/database.yml:/app/config/database.yml
      - ./docker/unicorn.rb:/app/config/unicorn.rb

  db:
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro

  cron:
    build:
      context: .
    volumes:
      - ./docker/database.yml:/app/config/database.yml
      - .:/app
